import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MyClassFactory from "./factories/MyClassFactory";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  try {
    await MyClassFactory.loadModules();  // Cargar dinámicamente las clases
    console.log('Dynamic modules loaded successfully.');
  } catch (error) {
    console.error('Error loading dynamic modules:', error);
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
